### ISSUE TITLE
Forms using Blade and the @sessionToken directive don't work

### ISSUE THREAD

**Issue by SebKay** [Kyon147/laravel-shopify#239]
I've just upgrade to v19.1.0 (from the old Osiset package) and whenever I submit a form that uses the `@sessionToken` Blade directive, the page just hangs (see screenshot).

![Screenshot 2023-11-22 at 21 04 15](https://github.com/Kyon147/laravel-shopify/assets/1873695/82212c2f-b988-4ba3-9f32-3d37be86c010)

The controller is actually processed because the code in my controller method is being run, it's the redirect after that which fails.

It appears the issue is with `Redirect::tokenRedirect()`.

So far as I can tell, it hits the `authenticate/token` route and gets stuck (I figured that bit out thanks to Laravel Debugbar).

It's worth noting there's nothing in the error log either.

Do you have any idea why this might be happening and what I can do to fix it?

**Comment by Kyon147** [comment]
This should be fixed in 19.2.0 now, can you upgrade and try. Re-open if still and issue.

**Comment by SebKay** [comment]
Yep! Seems to be fixed.

Just a heads up, this is still an issue when using an app via the new Shopify admin URL, but if you're app is on the old URL then it works fine.

**Comment by SebKay** [comment]
OK, upon testing this is still an issue, however now it's intermittent instead of all the time.

**Comment by SebKay** [comment]
Opened a new issue for this, #248.
